"use client";

import { useParams } from "next/navigation";

const Checkout: React.FC = () => {
  const params = useParams();
  const { country, userId } = params;
  console.log({
    country,
    userId
  });
  

  return (
    <div className="p-6 text-center">
      <h1 className="text-2xl font-bold mb-4">Checkout Page</h1>
      <p className="text-lg">Country: <strong>{country}</strong></p>
      <p className="text-lg">Generated by User ID: <strong>{userId}</strong></p>
    </div>
  );
};

export default Checkout;
